In [1]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.loaders import list_excel_sheets, load_excel_sheet
from src.utils import RAW_SOURCE_DIRS

from src.parsers.qilt import parse_qilt_sheet, find_all_qilt_sheets

In [2]:
qilt_folder = "QILT"
gos_excel_file_name = "QILT-2024-GOS"

gos_excel_file = RAW_SOURCE_DIRS[qilt_folder][gos_excel_file_name]

gos_excel_sheets = list_excel_sheets(qilt_folder, gos_excel_file)
gos_excel_sheet = gos_excel_sheets[1] # ! the test one

df = load_excel_sheet(qilt_folder, gos_excel_file, gos_excel_sheet)
df

,"Employment (FTE, OE, LF, SAL) and study outcomes among all course levels from all provider types by provider type, 2023 - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Back to INDEX,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Full-time employment,Overall employment,Labour force participation rate,Median annual full-time salaries ($),In full-time study (%)
3,Undergraduate 2023,Universities,79.4,89.1,92.6,"71,000",18.0
4,Undergraduate 2023,NUHEIs,65.3,83.4,89.3,"65,600",17.9
5,Undergraduate 2023,All institutions,79.0,88.9,92.5,"71,000",18.0
6,Undergraduate 2024,Universities,74.4,87.1,92.7,"75,000",17.9
7,Undergraduate 2024,NUHEIs,61.8,80.8,89.9,"70,000",19.4
8,Undergraduate 2024,All institutions,74.0,86.9,92.6,"75,000",17.9
9,Postgraduate coursework 2023,Universities,90.0,93.9,95.6,"97,000",7.1
10,Postgraduate coursework 2023,NUHEIs,92.7,94.3,95.6,"94,000",6.4
11,Postgraduate coursework 2023,All institutions,90.3,93.9,95.6,"96,600",7.1
12,Postgraduate coursework 2024,Universities,87.6,92.5,95.4,"101,000",7.4
13,Postgraduate coursework 2024,NUHEIs,91.9,93.6,95.3,"97,000",7.1
14,Postgraduate coursework 2024,All institutions,88.1,92.7,95.4,"100,000",7.3
15,Postgraduate research 2023,Universities,85.2,91.4,95.2,"100,000",6.9
16,Postgraduate research 2023,NUHEIs,NaN,NaN,NaN,NaN,NaN
17,Postgraduate research 2023,All institutions,85.3,91.4,95.2,"100,000",6.9
18,Postgraduate research 2024,Universities,82.8,90.5,95.1,"104,400",5.1
19,Postgraduate research 2024,NUHEIs,NaN,NaN,NaN,NaN,NaN
20,Postgraduate research 2024,All institutions,82.8,90.5,95.1,"104,400",5.1
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Column variables:,NaN,NaN,NaN,NaN,NaN,NaN
23,AVAILEMP,NaN,NaN,NaN,NaN,NaN,NaN
24,AVAILFT,NaN,NaN,NaN,NaN,NaN,NaN
25,FULLEMP,NaN,NaN,NaN,NaN,NaN,NaN
26,FURSTUD,NaN,NaN,NaN,NaN,NaN,NaN
27,GENEMP,NaN,NaN,NaN,NaN,NaN,NaN
28,SALARYA,NaN,NaN,NaN,NaN,NaN,NaN
29,TRIMSAL_ALL,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Column filters:,NaN,NaN,NaN,NaN,NaN,NaN
32,FTE: AVAILFT = 1,NaN,NaN,NaN,NaN,NaN,NaN
33,OE: AVAILEMP = 1,NaN,NaN,NaN,NaN,NaN,NaN
34,"SAL: FULLEMP = 1, TRIMSAL_ALL = 1",NaN,NaN,NaN,NaN,NaN,NaN
35,"FTS: FURSTUD = (1,2,5)",NaN,NaN,NaN,NaN,NaN,NaN
36,Data for all columns is filtered to: ANALYSIS ...,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Row variables:,NaN,NaN,NaN,NaN,NaN,NaN
39,HEPTYPE,NaN,NaN,NaN,NaN,NaN,NaN
40,YEAR,NaN,NaN,NaN,NaN,NaN,NaN
41,LEVEL,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Row notes:,NaN,NaN,NaN,NaN,NaN,NaN
44,Universites: HEPTYPE = 1,NaN,NaN,NaN,NaN,NaN,NaN
45,NUHEIs: HEPTYPE = 2,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
alternative_excel_sheet = gos_excel_sheets[4] # ! an alternative example

try:
    parsed_qilt_sheet = parse_qilt_sheet(qilt_folder, gos_excel_file, alternative_excel_sheet)
except ValueError:
    print("No header found")
else:
    print(parsed_qilt_sheet.name)
    parsed_qilt_sheet.table # ! a table, but yet to be cleaned

EMP_PGR_ALL_2Y_AREA

In [4]:
gos_excel_sheets_df = find_all_qilt_sheets(qilt_folder, gos_excel_file)
gos_excel_sheets_df # ! use these results to inform what is chosen

,Sheet name,Sheet title
Sheet number,,
1,INDEX,GOS 2024 Tables and Figures
2,OVERALL_ALL_ALL_2Y_HEPTYPE,"Employment (FTE, OE, LF, SAL) and study outcom..."
3,EMP_UG_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
4,EMP_PGC_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
5,EMP_PGR_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
...,...,...
155,CRSPREP_PGC_ALL_1Y_AREA,Course prepared them well or very well for cur...
156,CRSPREP_PGR_ALL_1Y_AREA,Course prepared them well or very well for cur...
157,CRSPREP_UG_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...
158,CRSPREP_PGC_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...
159,CRSPREP_PGR_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...

In [6]:
gos_l_excel_file_name = "QILT-2024-GOS-L" # ! data comparison, use ChatGPT to see what is common
gos_l_excel_file = RAW_SOURCE_DIRS[qilt_folder][gos_l_excel_file_name]
gos_l_excel_sheets_df = find_all_qilt_sheets(qilt_folder, gos_l_excel_file)
gos_l_excel_sheets_df

,Sheet name,Sheet title
Sheet number,,
1,INDEX,GOS-L 2024 Tables and Figures
2,FTE_UG_ALL_5Y,Short-term and medium-term domestic full-time ...
3,FTE_ALL_ALL_1Y_AREA,Short-term and medium-term full-time domestic ...
4,STMT_UG_ALL_3Y,Short-term and medium-term domestic employment...
5,STMT_PGC_ALL_3Y,Short-term and medium-term domestic employment...
...,...,...
158,STMT_PGR_ALL_1Y_SG,Short-term and medium-term domestic employment...
159,STMT_UG_ALL_1Y_E315,Short-term and medium-term domestic employment...
160,STMT_UG_ALL_1Y_HEPTYPE,Short-term and medium-term domestic employment...
161,STMT_UG_ALL_1Y_SG,Short-term and medium-term domestic employment...
162,SPOQ_ALL_ALL_1Y_E942,Occupation does not fully use skills or educat...