In [15]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.loaders import list_excel_sheets, load_excel_sheet
from src.utils import RAW_SOURCE_DIRS

from src.parsers.qilt import parse_qilt_sheet

In [ ]:
qilt_folder = "QILT"
gos_excel_file_name = "QILT-2024-GOS"

gos_excel_file = RAW_SOURCE_DIRS[qilt_folder][gos_excel_file_name]

gos_excel_sheets = list_excel_sheets(qilt_folder, gos_excel_file)
gos_excel_sheet = gos_excel_sheets[1] # ! the test one

df = load_excel_sheet(qilt_folder, gos_excel_file, gos_excel_sheet)
df

,"Employment (FTE, OE, LF, SAL) and study outcomes among all course levels from all provider types by provider type, 2023 - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Back to INDEX,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Full-time employment,Overall employment,Labour force participation rate,Median annual full-time salaries ($),In full-time study (%)
3,Undergraduate 2023,Universities,79.4,89.1,92.6,"71,000",18.0
4,Undergraduate 2023,NUHEIs,65.3,83.4,89.3,"65,600",17.9
5,Undergraduate 2023,All institutions,79.0,88.9,92.5,"71,000",18.0
6,Undergraduate 2024,Universities,74.4,87.1,92.7,"75,000",17.9
7,Undergraduate 2024,NUHEIs,61.8,80.8,89.9,"70,000",19.4
8,Undergraduate 2024,All institutions,74.0,86.9,92.6,"75,000",17.9
9,Postgraduate coursework 2023,Universities,90.0,93.9,95.6,"97,000",7.1
10,Postgraduate coursework 2023,NUHEIs,92.7,94.3,95.6,"94,000",6.4
11,Postgraduate coursework 2023,All institutions,90.3,93.9,95.6,"96,600",7.1
12,Postgraduate coursework 2024,Universities,87.6,92.5,95.4,"101,000",7.4
13,Postgraduate coursework 2024,NUHEIs,91.9,93.6,95.3,"97,000",7.1
14,Postgraduate coursework 2024,All institutions,88.1,92.7,95.4,"100,000",7.3
15,Postgraduate research 2023,Universities,85.2,91.4,95.2,"100,000",6.9
16,Postgraduate research 2023,NUHEIs,NaN,NaN,NaN,NaN,NaN
17,Postgraduate research 2023,All institutions,85.3,91.4,95.2,"100,000",6.9
18,Postgraduate research 2024,Universities,82.8,90.5,95.1,"104,400",5.1
19,Postgraduate research 2024,NUHEIs,NaN,NaN,NaN,NaN,NaN
20,Postgraduate research 2024,All institutions,82.8,90.5,95.1,"104,400",5.1
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Column variables:,NaN,NaN,NaN,NaN,NaN,NaN
23,AVAILEMP,NaN,NaN,NaN,NaN,NaN,NaN
24,AVAILFT,NaN,NaN,NaN,NaN,NaN,NaN
25,FULLEMP,NaN,NaN,NaN,NaN,NaN,NaN
26,FURSTUD,NaN,NaN,NaN,NaN,NaN,NaN
27,GENEMP,NaN,NaN,NaN,NaN,NaN,NaN
28,SALARYA,NaN,NaN,NaN,NaN,NaN,NaN
29,TRIMSAL_ALL,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Column filters:,NaN,NaN,NaN,NaN,NaN,NaN
32,FTE: AVAILFT = 1,NaN,NaN,NaN,NaN,NaN,NaN
33,OE: AVAILEMP = 1,NaN,NaN,NaN,NaN,NaN,NaN
34,"SAL: FULLEMP = 1, TRIMSAL_ALL = 1",NaN,NaN,NaN,NaN,NaN,NaN
35,"FTS: FURSTUD = (1,2,5)",NaN,NaN,NaN,NaN,NaN,NaN
36,Data for all columns is filtered to: ANALYSIS ...,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Row variables:,NaN,NaN,NaN,NaN,NaN,NaN
39,HEPTYPE,NaN,NaN,NaN,NaN,NaN,NaN
40,YEAR,NaN,NaN,NaN,NaN,NaN,NaN
41,LEVEL,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Row notes:,NaN,NaN,NaN,NaN,NaN,NaN
44,Universites: HEPTYPE = 1,NaN,NaN,NaN,NaN,NaN,NaN
45,NUHEIs: HEPTYPE = 2,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
alternative_excel_sheet = gos_excel_sheets[4] # ! an alternative example
parsed_qilt_sheet = parse_qilt_sheet(qilt_folder, gos_excel_file, alternative_excel_sheet)

print(parsed_qilt_sheet.title)
parsed_qilt_sheet.table # ! a table, but yet to be cleaned

Employment outcomes (FTE, OE, LF), 2023-2024 among postgraduate research students from all provider types by study area

,unnamed_header_1,Full-time employment 2023,Full-time employment 2024,Overall employment 2023,Overall employment 2024,Labour force participation rate 2023,Labour force participation rate 2024,30 years or under 2023,30 years or under 2024
0,Agriculture and environmental studies,83.7,82.6,96.2,89.0,97.2,99.0,29.6,31.7
1,Architecture and built environment,76.7,66.7,84.8,83.3,97.1,100.0,8.8,11.1
2,Business and management,85.8,83.3,94.2,90.0,95.9,92.7,12.2,13.7
3,Communications,80.0,72.4,88.6,90.0,92.1,93.0,21.1,20.9
4,Computing and information systems,86.3,75.7,85.9,85.4,97.5,95.3,20.0,22.1
5,Creative arts,83.0,73.4,92.9,87.9,93.9,91.8,15.0,24.0
6,Dentistry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Engineering,85.5,81.3,89.2,87.9,96.9,97.1,30.4,32.4
8,Health services and support,92.2,89.6,96.5,94.0,96.3,97.4,27.0,20.1
9,"Humanities, culture and social sciences",79.4,74.0,89.2,88.2,89.1,90.2,21.6,19.8
10,Law and paralegal studies,84.9,81.1,92.6,87.5,98.6,97.0,10.1,10.6
11,Medicine,86.0,90.7,90.3,93.7,97.2,94.7,29.6,27.3
12,Nursing,90.9,87.0,90.6,89.3,98.1,94.9,13.0,5.1
13,Pharmacy,83.3,89.5,87.5,90.9,100.0,97.8,50.0,48.9
14,Psychology,92.6,88.3,95.8,94.7,98.2,95.9,50.5,41.1
15,Rehabilitation,NaN,NaN,100.0,NaN,100.0,NaN,11.5,NaN
16,Science and mathematics,83.9,85.1,89.5,90.9,96.3,96.6,51.3,53.6
17,Social work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Teacher education,87.4,84.2,94.1,91.4,94.4,98.2,4.7,2.7
19,"Tourism, hospitality, personal services, sport...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Veterinary science,NaN,NaN,92.3,NaN,100.0,NaN,42.3,NaN
21,Total,85.3,82.8,91.4,90.5,95.2,95.1,29.8,29.2
22,Standard deviation,10.5,8.8,7.2,4.7,3.2,4.3,16.0,13.9

In [18]:
from pprint import pprint

print(len(gos_excel_sheets)) 
pprint(gos_excel_sheets) # ! use these results to inform what is chosen

159
['INDEX',
 'OVERALL_ALL_ALL_2Y_HEPTYPE',
 'EMP_UG_ALL_2Y_AREA',
 'EMP_PGC_ALL_2Y_AREA',
 'EMP_PGR_ALL_2Y_AREA',
 'EMP_UG_ALL_2Y_E315',
 'EMP_PGC_ALL_2Y_E315',
 'EMP_PGR_ALL_2Y_E315',
 'EMP_UG_ALL_2Y_DG',
 'EMP_PGC_ALL_2Y_DG',
 'EMP_PGR_ALL_2Y_DG',
 'EMP_UG_ALL_1Y_FTS',
 'EMP_PGC_ALL_1Y_FTS',
 'EMP_PGR_ALL_1Y_FTS',
 'EMP_UG_ALL_2Y_AREA45',
 'EMP_PGC_ALL_2Y_AREA45',
 'EMP_PGR_ALL_2Y_AREA45',
 'EMP_UG_UNI_2Y_AREA',
 'EMP_UG_NUHEI_2Y_AREA',
 'EMP_UG_UNI_2Y_DG',
 'EMP_UG_NUHEI_2Y_DG',
 'EMP_UG_ALL_3Y_PERIOD',
 'EMP_PGC_ALL_3Y_PERIOD',
 'EMP_PGR_ALL_3Y_PERIOD',
 'SAL_UG_ALL_2Y_AREA_E315',
 'SAL_PGC_ALL_2Y_AREA_E315',
 'SAL_PGR_ALL_2Y_AREA_E315',
 'SAL_UG_ALL_2Y_DG_E315',
 'SAL_PGC_ALL_2Y_DG_E315',
 'SAL_PGR_ALL_2Y_DG_E315',
 'SAL_UG_ALL_2Y_AREA45_E315',
 'SAL_PGC_ALL_2Y_AREA45_E315',
 'SAL_PGR_ALL_2Y_AREA45_E315',
 'LF_UG_UNI_1Y_INST_CI',
 'LF_UG_UNI_3YP_INST_CI',
 'LF_PGC_UNI_1Y_INST_CI',
 'LF_PGC_UNI_3YP_INST_CI',
 'LF_PGR_UNI_3YP_INST_CI',
 'LF_UG_NUHEI_3YP_INST_CI',
 'LF_PGC_NUHEI_3YP_INST_CI',
 'LF_UG_UNI_2Y_E315',
 'LF_UG_NUHEI_2Y_E315',
 'PREFMHRS_UG_ALL_1Y_E315',
 'PREFMHRS_PGC_ALL_1Y_E315',
 'PREFMHRS_PGR_ALL_1Y_E315',
 'PARTEMP_UG_ALL_1Y_AREA_E315',
 'RSNOMORE_UG_ALL_1Y_E315',
 'RSNOMORE_PGC_ALL_1Y_E315',
 'RSNOMORE_PGR_ALL_1Y_E315',
 'RSOVRQ_UG_ALL_1Y',
 'RSOVRQ_PGC_ALL_1Y',
 'RSOVRQ_PGR_ALL_1Y',
 'RSOVRQ_UG_ALL_1Y_AREA',
 'RSOVRQ_PGC_ALL_1Y_AREA',
 'RSOVRQ_PGR_ALL_1Y_AREA',
 'FTS_UG_ALL_1Y_AREA_E315',
 'FTS_PGC_ALL_1Y_AREA_E315',
 'FTS_PGR_ALL_1Y_AREA_E315',
 'FTS_UG_ALL_1Y_BFOE',
 'FTS_PGC_ALL_1Y_BFOE',
 'FTS_PGR_ALL_1Y_BFOE',
 'FTS_UG_ALL_1Y_FURFOE',
 'FTS_PGC_ALL_1Y_FURFOE',
 'FTS_PGR_ALL_1Y_FURFOE',
 'FTS_ALL_ALL_1Y_FURLEV',
 'FTS_UG_ALL_1Y_BFOE_FURFOE',
 'FTS_PGC_ALL_1Y_BFOE_FURFOE',
 'FTS_PGR_ALL_1Y_BFOE_FURFOE',
 'FTS_UG_ALL_1Y_DG',
 'FTS_PGC_ALL_1Y_DG',
 'FTS_PGR_ALL_1Y_DG',
 'SAT_UG_ALL_2Y',
 'SAT_PGC_ALL_2Y',
 'SAT_PGR_ALL_2Y',
 'SAT_UG_ALL_2Y_AREA',
 'SAT_PGC_ALL_2Y_AREA',
 'SAT_PGR_ALL_2Y_AREA',
 'SAT_UG_ALL_2Y_DG',
 'SAT_PGC_ALL_2Y_DG',
 'SAT_PGR_ALL_2Y_DG',
 'SAT_UG_UNI_2Y_AREA',
 'SAT_UG_NUHEI_2Y_AREA',
 'SUMMARY_ALL_ALL_1Y',
 'SUMMARY_ALL_ALL_1Y_1P',
 'SUMMARY_ALL_ALL_1Y_2P',
 'SUMMARY_ALL_ALL_1Y_3P',
 'RR_ALL_UNI_1Y_INST',
 'RR_ALL_NUHEI_1Y_INST',
 'RR_UG_ALL_1Y',
 'RR_PGC_ALL_1Y',
 'RR_PGR_ALL_1Y',
 'CHAR_ALL_ALL_1Y_TYPE',
 'CHAR_ALL_ALL_1Y_DOM_TYPE',
 'CHAR_UG_ALL_1Y_DOM_TYPE',
 'CHAR_PGC_ALL_1Y_DOM_TYPE',
 'CHAR_PGR_ALL_1Y_DOM_TYPE',
 'CHAR_ALL_ALL_1Y_AREA',
 'OCC_UG_ALL_1Y_EMPTYPE_E315',
 'OCC_PGC_ALL_1Y_EMPTYPE_E315',
 'OCC_PGR_ALL_1Y_EMPTYPE_E315',
 'OCCO_UG_ALL_1Y_AREA45',
 'OCC_UG_UNI_1Y_EMPTYPE_E315',
 'OCC_UG_NUHEI_1Y_EMPTYPE_E315',
 'OCCO_UG_UNI_1Y_AREA_EMPTYPE',
 'OCCO_UG_ALL_1Y_AREA_EMPTYPE',
 'QUALIMP_UG_ALL_1Y',
 'QUALIMP_PGC_ALL_1Y',
 'QUALIMP_PGR_ALL_1Y',
 'CRSPREP_UG_ALL_1Y',
 'CRSPREP_PGC_ALL_1Y',
 'CRSPREP_PGR_ALL_1Y',
 'SPOQSCL_ALL_ALL_1Y',
 'HOURS_UG_ALL_3Y',
 'HOURS_PGC_ALL_3Y',
 'HOURS_PGR_ALL_3Y',
 'HOURS_UG_ALL_3Y_PERIOD',
 'HOURS_PGC_ALL_3Y_PERIOD',
 'HOURS_PGR_ALL_3Y_PERIOD',
 'AWAYWORK_UG_ALL_3Y',
 'AWAYWORK_PGC_ALL_3Y',
 'AWAYWORK_PGR_ALL_3Y',
 'AWAYWORK_UG_ALL_3Y_PERIOD',
 'AWAYWORK_PGC_ALL_3Y_PERIOD',
 'AWAYWORK_PGR_ALL_3Y_PERIOD',
 'FTE_UG_UNI_1Y_INST_FIG',
 'FTE_UG_UNI_3YP_INST_FIG',
 'SAL_UG_UNI_1Y_INST_FIG',
 'SAL_UG_UNI_3YP_INST_FIG',
 'FTE_UG_NUHEI_3YP_INST_FIG',
 'SAL_UG_NUHEI_3YP_INST_FIG',
 'FTE_PGC_UNI_1Y_INST_FIG',
 'FTE_PGC_UNI_3YP_INST_FIG',
 'FTE_PGC_NUHEI_3YP_INST_FIG',
 'FTE_PGR_UNI_3YP_INST_FIG',
 'SAL_PGC_UNI_1Y_INST_FIG',
 'SAL_PGC_UNI_3YP_INST_FIG',
 'SAL_PGC_NUHEI_3YP_INST_FIG',
 'SAL_PGR_UNI_3YP_INST_FIG',
 'OCCF_UG_ALL_1Y_BFOE',
 'OCCF_PGC_ALL_1Y_BFOE',
 'OCCF_PGR_ALL_1Y_BFOE',
 'OCCO_UG_ALL_1Y_BFOE',
 'OCCO_PGC_ALL_1Y_BFOE',
 'OCCO_PGR_ALL_1Y_BFOE',
 'OCCF_UG_ALL_1Y_AREA',
 'OCCF_PGC_ALL_1Y_AREA',
 'OCCF_PGR_ALL_1Y_AREA',
 'OCCO_UG_ALL_1Y_AREA',
 'OCCO_PGC_ALL_1Y_AREA',
 'OCCO_PGR_ALL_1Y_AREA',
 'SPOQSCL_UG_ALL_1Y_AREA',
 'SPOQSCL_PGC_ALL_1Y_AREA',
 'SPOQSCL_PGR_ALL_1Y_AREA',
 'CRSPREP_UG_ALL_1Y_AREA',
 'CRSPREP_PGC_ALL_1Y_AREA',
 'CRSPREP_PGR_ALL_1Y_AREA',
 'CRSPREP_UG_ALL_1Y_AREA_OCCF',
 'CRSPREP_PGC_ALL_1Y_AREA_OCCF',
 'CRSPREP_PGR_ALL_1Y_AREA_OCCF']

In [ ]:
gos_l_excel_file_name = "QILT-2024-GOS-L" # ! data comparison, use ChatGPT to see what is common

gos_l_excel_file = RAW_SOURCE_DIRS[qilt_folder][gos_l_excel_file_name]

gos_l_excel_sheets = list_excel_sheets(qilt_folder, gos_l_excel_file)
print(len(gos_l_excel_sheets)) 
pprint(gos_l_excel_sheets)

162
['INDEX',
 'FTE_UG_ALL_5Y',
 'FTE_ALL_ALL_1Y_AREA',
 'STMT_UG_ALL_3Y',
 'STMT_PGC_ALL_3Y',
 'STMT_PGR_ALL_3Y',
 'STMT_UG_ALL_1Y_AREA',
 'STMT_PGC_ALL_1Y_AREA',
 'STMT_PGR_ALL_1Y_AREA',
 'STMT_UG_ALL_1Y_AREA45',
 'STMT_PGC_ALL_1Y_AREA45',
 'STMT_PGR_ALL_1Y_AREA45',
 'STMT_UG_ALL_1Y_ARSX',
 'STMT_PGC_ALL_1Y_ARSX',
 'HOURS_UG_ALL_3Y',
 'HOURS_PGC_ALL_3Y',
 'HOURS_PGR_ALL_3Y',
 'AWAY_UG_ALL_3Y',
 'AWAY_PGC_ALL_3Y',
 'AWAY_PGR_ALL_3Y',
 'OCCO_UG_ALL_1Y_AREA',
 'OCCO_PGC_ALL_1Y_AREA',
 'OCCO_PGR_ALL_1Y_AREA',
 'OCCF_UG_ALL_1Y_AREA',
 'OCCF_PGC_ALL_1Y_AREA',
 'OCCF_PGR_ALL_1Y_AREA',
 'RSOVRQ_UG_ALL_1Y_AREA',
 'RSOVRQ_PGC_ALL_1Y_AREA',
 'RSOVRQ_PGR_ALL_1Y_AREA',
 'RSOVRQ_UG_ALL_1Y_MT',
 'RSOVRQ_UG_ALL_1Y_STMT2',
 'RSOVRQ_PGC_ALL_1Y_STMT2',
 'RSOVRQ_PGR_ALL_1Y_STMT2',
 'STMT2_UG_UNI_1Y_INST_CI',
 'STMT2_UG_UNI_3YP_INST_CI',
 'STMT2_PGC_UNI_1Y_INST_CI',
 'STMT2_PGC_UNI_3YP_INST_CI',
 'STMT3_UG_UNI_1Y_INST_CI',
 'STMT3_UG_UNI_3YP_INST_CI',
 'STMT3_PGC_UNI_1Y_INST_CI',
 'STMT3_PGC_UNI_3YP_INST_CI',
 'LFT_UG_ALL_1Y',
 'LFT_PGC_ALL_1Y',
 'LFT_PGR_ALL_1Y',
 'QUALIMP_UG_ALL_1Y_STMT2',
 'QUALIMP_PGC_ALL_1Y_STMT2',
 'QUALIMP_PGR_ALL_1Y_STMT2',
 'CRSPREP_UG_ALL_1Y_STMT2',
 'CRSPREP_PGC_ALL_1Y_STMT2',
 'CRSPREP_PGR_ALL_1Y_STMT2',
 'GAS_UG_ALL_1Y_AREA',
 'GAS_PGC_ALL_1Y_AREA',
 'GAS_UG_ALL_1Y_STMT2',
 'GAS_PGC_ALL_1Y_STMT2',
 'GAS_PGR_ALL_1Y_STMT2',
 'OV_ALL_ALL_1Y',
 'INST_ALL_ALL_5Y',
 'RR_ALL_UNI_1Y_INST',
 'RR_ALL_NUHEI_1Y_INST',
 'RR_UG_UNI_1Y_INST',
 'RR_UG_NUHEI_1Y_INST',
 'RR_PGC_UNI_1Y_INST',
 'RR_PGC_NUHEI_1Y_INST',
 'RR_PGR_UNI_1Y_INST',
 'RR_PGR_NUHEI_1Y_INST',
 'CHAR_ALL_ALL_1Y_AREA',
 'CHAR_ALL_ALL_1Y_AREA_INT',
 'CHAR_UG_ALL_1Y_AREA',
 'CHAR_UG_ALL_1Y_AREA_INT',
 'CHAR_PGC_ALL_1Y_AREA',
 'CHAR_PGC_ALL_1Y_AREA_INT',
 'CHAR_PGR_ALL_1Y_AREA',
 'CHAR_PGR_ALL_1Y_AREA_INT',
 'CHAR_UG_ALL_1Y_ARSX',
 'CHAR_PGC_ALL_1Y_ARSX',
 'CHAR_PGR_ALL_1Y_ARSX',
 'CHAR_UG_ALL_1Y_AR45SX',
 'CHAR_PGC_ALL_1Y_AR45SX',
 'CHAR_PGR_ALL_1Y_AR45SX',
 'CHAR_ALL_ALL_1Y_SG',
 'CHAR_UG_ALL_1Y_SG',
 'CHAR_PGC_ALL_1Y_SG',
 'CHAR_PGR_ALL_1Y_SG',
 'FTE_UG_UNI_1Y_INST_FIG',
 'FTE_UG_UNI_3YP_INST_FIG',
 'FTE_PGC_UNI_1Y_INST_FIG',
 'FTE_PGC_UNI_3YP_INST_FIG',
 'SAL_UG_UNI_1Y_INST_FIG',
 'SAL_UG_UNI_3YP_INST_FIG',
 'SAL_PGC_UNI_1Y_INST_FIG',
 'SAL_PGC_UNI_3YP_INST_FIG',
 'FTE_ALL_ALL_1Y_AREA45',
 'FTE_PGC_UNI_1Y_INST_CI',
 'FTE_UG_UNI_1Y_INST_CI',
 'STMT_UG_ALL_1Y',
 'STMT_PGC_ALL_1Y',
 'STMT_PGR_ALL_1Y',
 'EHIST_UG_ALL_1Y',
 'EHIST_PGC_ALL_1Y',
 'EHIST_PGR_ALL_1Y',
 'EHIST_UG_ALL_1Y_FTS',
 'STMT_UG_ALL_1Y_FTS',
 'FTE_ALL_ALL_1Y_AREA_INT',
 'FTE_UG_ALL_5Y_HEPTYPE',
 'FTS_ALL_ALL_1Y_E942',
 'FTS_ALL_ALL_1Y_HEPTYPE',
 'FTS_UG_ALL_1Y_AREA',
 'FTS_PGC_ALL_1Y_AREA',
 'FTS_PGR_ALL_1Y_AREA',
 'FTS_UG_ALL_1Y_BFOE',
 'FTS_PGC_ALL_1Y_BFOE',
 'FTS_PGR_ALL_1Y_BFOE',
 'FTS_UG_ALL_1Y_BFOE_INT',
 'FTS_PGC_ALL_1Y_BFOE_INT',
 'FTS_PGR_ALL_1Y_BFOE_INT',
 'FTS_UG_ALL_1Y_SG',
 'FTS_UG_ALL_1Y_FURFOE',
 'FTS_PGC_ALL_1Y_FURFOE',
 'FTS_PGR_ALL_1Y_FURFOE',
 'FTS_UG_ALL_1Y_FURFOE_INT',
 'FTS_PGC_ALL_1Y_FURFOE_INT',
 'FTS_PGR_ALL_1Y_FURFOE_INT',
 'LFT_PGC_ALL_1Y_E315',
 'LFT_PGR_ALL_1Y_E315',
 'LFT_UG_ALL_1Y_E315',
 'OCC_PGC_ALL_1Y_STMT2_E315',
 'OCC_PGC_ALL_1Y_STMT2_E942',
 'OCC_PGR_ALL_1Y_STMT2_E315',
 'OCC_PGR_ALL_1Y_STMT2_E942',
 'OCC_UG_ALL_1Y_STMT2_E315',
 'OCC_UG_ALL_1Y_STMT2_E942',
 'OCCF_PGC_ALL_1Y_BFOE',
 'OCCF_PGR_ALL_1Y_BFOE',
 'OCCF_UG_ALL_1Y_BFOE',
 'OCCO_PGC_ALL_1Y_BFOE',
 'OCCO_PGR_ALL_1Y_BFOE',
 'OCCO_UG_ALL_1Y_BFOE',
 'PREFMHRS_UG_ALL_1Y_E315',
 'PREFMHRS_UG_ALL_1Y_E942',
 'PREFMHRS_PGC_ALL_1Y_E315',
 'PREFMHRS_PGC_ALL_1Y_E942',
 'PREFMHRS_PGR_ALL_1Y_E315',
 'PREFMHRS_PGR_ALL_1Y_E942',
 'RSNOMORE_PGC_ALL_1Y_STMT_E315',
 'RSNOMORE_PGC_ALL_1Y_STMT_E942',
 'RSNOMORE_PGR_ALL_1Y_STMT_E315',
 'RSNOMORE_PGR_ALL_1Y_STMT_E942',
 'RSNOMORE_UG_ALL_1Y_STMT_E315',
 'RSNOMORE_UG_ALL_1Y_STMT_E942',
 'RSOVRQ_PGC_ALL_1Y_MT',
 'RSOVRQ_PGR_ALL_1Y_MT',
 'STMT_ALL_ALL_1Y_E942',
 'STMT_PGC_ALL_1Y_E315',
 'STMT_PGC_ALL_1Y_HEPTYPE',
 'STMT_PGC_ALL_1Y_SG',
 'STMT_PGR_ALL_1Y_E315',
 'STMT_PGR_ALL_1Y_HEPTYPE',
 'STMT_PGR_ALL_1Y_SG',
 'STMT_UG_ALL_1Y_E315',
 'STMT_UG_ALL_1Y_HEPTYPE',
 'STMT_UG_ALL_1Y_SG',
 'SPOQ_ALL_ALL_1Y_E942']