In [ ]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.preparation.qilt import prepare_qilt_sheet
from src.types import ExcelSheet

In [3]:
gos_9_sheet = ExcelSheet(
    folder="QILT", 
    data_source="QILT-2024-GOS", 
    sheet_name="EMP_UG_ALL_2Y_DG"
) # GOS 9

gos_9_table = prepare_qilt_sheet(gos_9_sheet.folder, gos_9_sheet.file_name, gos_9_sheet.sheet_name).table
gos_9_table

,row_group,row_label,full_time_employment_2023,full_time_employment_2024,overall_employment_2023,overall_employment_2024,labour_force_participation_rate_2023,labour_force_participation_rate_2024
0,Gender,Male,78.2,72.7,87.0,84.7,92.5,92.0
1,Gender,Female,79.5,74.9,89.9,88.0,92.5,92.9
2,Age group,30 years or under,78.0,72.4,88.7,86.5,93.2,93.3
3,Age group,Over 30 years,82.7,80.1,89.7,88.4,90.0,90.4
4,Indigenous,Indigenous,82.8,82.7,88.0,88.8,92.2,91.5
5,Indigenous,Non-Indigenous,78.9,73.9,89.0,86.9,92.5,92.6
6,Home language,English,79.3,74.5,89.2,87.3,92.5,92.7
7,Home language,Language other than English,66.1,58.1,78.4,73.6,90.4,88.5
8,Disability,Disability reported,71.0,66.8,84.3,82.9,88.7,89.8
9,Disability,No disability reported,79.9,75.0,89.5,87.4,93.0,93.0
10,Study mode,Internal/Mixed study mode,77.4,71.9,88.6,86.2,92.8,92.8
11,Study mode,External study mode,84.7,81.2,90.6,89.5,91.6,92.0
12,First in family,First in family,79.6,75.1,89.5,87.9,92.9,93.4
13,First in family,Not first in family,79.0,73.4,89.1,86.7,92.9,92.8
14,Socio-economic status,High*,79.5,73.5,89.6,86.7,92.1,92.2
15,Socio-economic status,Medium*,78.7,73.8,89.0,87.2,92.9,93.0
16,Socio-economic status,Low*,78.3,73.8,88.4,86.4,92.7,93.1
17,Locality,Metro* †,77.6,71.7,88.4,86.1,92.7,92.7
18,Locality,Regional/Remote* †,83.7,80.6,91.6,89.9,92.3,93.2
19,Total,Total,79.0,74.0,88.9,86.9,92.5,92.6

In [4]:
gos_l_161_sheet = ExcelSheet(
    folder="QILT", 
    data_source="QILT-2024-GOS-L", 
    sheet_name="STMT_UG_ALL_1Y_SG"
) # GOS-L 161
gos_l_161_table = prepare_qilt_sheet(gos_l_161_sheet.folder, gos_l_161_sheet.file_name, gos_l_161_sheet.sheet_name).table
gos_l_161_table

,row_group,row_label,short_term_full_time_employed,medium_term_full_time_employed,short_term_overall_employed,medium_term_overall_employed,short_term_labour_force_participation,medium_term_labour_force_participation,short_term_salaries,medium_term_salaries
0,Age group,30 and under,69.6,91.3,86.9,93.4,93.3,93.4,64300,86000
1,Age group,Over 30,74.6,90.4,86.6,93.0,91.1,91.0,72000,92700
2,Study mode,Internal/Mixed,69.3,91.0,86.2,93.1,92.9,92.9,65000,87000
3,Study mode,External,80.7,91.5,90.1,94.1,91.4,91.2,73100,93900
4,Gender,Male,71.2,90.9,85.0,92.5,92.2,92.7,68000,92000
5,Gender,Female,71.1,91.2,87.7,93.7,92.9,92.6,65000,85000
6,Indigenous,Indigenous,80.8,90.9,88.1,91.7,89.9,92.9,67700,92100
7,Indigenous,Non-Indigenous,70.9,91.1,86.8,93.3,92.7,92.7,65700,88000
8,Home language,English,71.3,91.1,87.1,93.3,92.7,92.7,66000,88300
9,Home language,Other,57.6,90.3,71.4,91.2,88.9,88.3,61300,83500
10,Disability,Disability reported,60.0,86.3,78.8,90.5,89.5,88.7,65400,84700
11,Disability,No disability reported,72.4,91.6,87.9,93.6,93.1,93.2,66000,88700
12,First in family,First in family**,70.6,88.6,86.0,90.7,89.9,90.9,65000,84000
13,First in family,Not first in family**,68.9,88.0,86.0,91.3,92.4,91.4,63400,88000
14,Socio-economic status,High***,72.0,91.5,87.4,93.1,92.9,92.5,66000,90000
15,Socio-economic status,Medium***,70.8,91.1,87.0,93.5,92.7,92.8,66000,87700
16,Socio-economic status,Low***,69.9,90.5,85.2,92.8,92.3,92.9,65400,86000
17,Locality,Metro*** †,69.5,91.0,86.2,93.1,93.2,92.9,65700,88100
18,Locality,Regional/Remote*** †,75.9,91.5,88.8,93.8,91.4,92.3,66000,88000
19,Total,Total,71.1,91.1,86.8,93.3,92.7,92.7,65800,88100

In [ ]:
from src.transform.subgroup_comparison import build_subgroup_comparison_table_from_tables

subgroup_comparison_table = build_subgroup_comparison_table_from_tables(gos_9_table, gos_l_161_table)
subgroup_comparison_table

,row_group,row_label,short_term_full_time_employment,medium_term_full_time_employment,full_time_employment_change,short_term_overall_employment,medium_term_overall_employment,overall_employment_change,short_term_labour_force_participation,medium_term_labour_force_participation,labour_force_participation_change
0,Gender,Male,72.7,90.9,18.2,84.7,92.5,7.8,92.0,92.7,0.7
1,Gender,Female,74.9,91.2,16.3,88.0,93.7,5.7,92.9,92.6,-0.3
2,Age group,30 years or under,72.4,91.3,18.9,86.5,93.4,6.9,93.3,93.4,0.1
3,Age group,Over 30 years,80.1,90.4,10.3,88.4,93.0,4.6,90.4,91.0,0.6
4,Indigenous,Indigenous,82.7,90.9,8.2,88.8,91.7,2.9,91.5,92.9,1.4
5,Indigenous,Non-Indigenous,73.9,91.1,17.2,86.9,93.3,6.4,92.6,92.7,0.1
6,Home language,English,74.5,91.1,16.6,87.3,93.3,6.0,92.7,92.7,0.0
7,Home language,Language other than English,58.1,90.3,32.2,73.6,91.2,17.6,88.5,88.3,-0.2
8,Disability,Disability reported,66.8,86.3,19.5,82.9,90.5,7.6,89.8,88.7,-1.1
9,Disability,No disability reported,75.0,91.6,16.6,87.4,93.6,6.2,93.0,93.2,0.2
10,Study mode,Internal/Mixed study mode,71.9,91.0,19.1,86.2,93.1,6.9,92.8,92.9,0.1
11,Study mode,External study mode,81.2,91.5,10.3,89.5,94.1,4.6,92.0,91.2,-0.8
12,First in family,First in family,75.1,88.6,13.5,87.9,90.7,2.8,93.4,90.9,-2.5
13,First in family,Not first in family,73.4,88.0,14.6,86.7,91.3,4.6,92.8,91.4,-1.4
14,Socio-economic status,High,73.5,91.5,18.0,86.7,93.1,6.4,92.2,92.5,0.3
15,Socio-economic status,Medium,73.8,91.1,17.3,87.2,93.5,6.3,93.0,92.8,-0.2
16,Socio-economic status,Low,73.8,90.5,16.7,86.4,92.8,6.4,93.1,92.9,-0.2
17,Locality,Metro,71.7,91.0,19.3,86.1,93.1,7.0,92.7,92.9,0.2
18,Locality,Regional/Remote,80.6,91.5,10.9,89.9,93.8,3.9,93.2,92.3,-0.9
19,Total,Total,74.0,91.1,17.1,86.9,93.3,6.4,92.6,92.7,0.1